version: '2'
services:
    contracts-app:
        image: contracts
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://contracts-postgresql:5432/contracts
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=contracts-elasticsearch:9300
        ports:
            - 8080:8080
    contracts-postgresql:
        extends:
            file: postgresql.yml
            service: contracts-postgresql
    contracts-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: contracts-elasticsearch
